name: Mutational Fuzzer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: default

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Java Sources
        run: |
          mkdir -p build
          javac -d build $(find . -name "*.java")

      - name: Run Fuzzer
        run: |
          java -cp build your.package.MainFuzzerClass
